/**
 * General-purpose tokenizer for spaceless orthographies.
 *
 * Loads a pre-scraped word list (generated by autotok_scraper.py from
 * the language's autotok.hfst) into an in-memory hash set, then applies
 * LRLM (Left-to-Right Longest Match) to insert word boundaries.
 *
 * Usage: ./tokeniser <wordlist.txt>
 *   wordlist.txt: output of autotok_scraper.py (sections marked "!!!!<N>")
 *
 * Reads from stdin, writes space-separated tokens to stdout.
 * Passes non-alphabet characters through unchanged.
 */

#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <unordered_set>
#include <stdexcept>

// Maximum word length to try in LRLM (read from word list headers "!!!!<N>")
static int g_max_word_len = 1;

// In-memory word set loaded from the word list file
static std::unordered_set<std::string> g_words;

// Set of individual Unicode chars that appear in any word in the word list.
// Used to identify which chars should be tokenised vs. passed through unchanged.
static std::unordered_set<std::string> g_alphabet;

// ---------------------------------------------------------------------------
// UTF-8 helpers
// ---------------------------------------------------------------------------

// Return the byte length of the UTF-8 character starting at s[i].
static int utf8_char_len(const std::string& s, size_t i) {
    unsigned char b = (unsigned char)s[i];
    if ((b & 0x80) == 0)    return 1;
    if ((b & 0xE0) == 0xC0) return 2;
    if ((b & 0xF0) == 0xE0) return 3;
    if ((b & 0xF8) == 0xF0) return 4;
    return 1;
}

// Split a UTF-8 string into (byte_offset, byte_length) pairs for each char.
static std::vector<std::pair<size_t,int>> utf8_offsets(const std::string& s) {
    std::vector<std::pair<size_t,int>> result;
    size_t i = 0;
    while (i < s.size()) {
        int len = utf8_char_len(s, i);
        result.push_back({i, len});
        i += len;
    }
    return result;
}

// Extract the single UTF-8 character at byte offset i in s.
static std::string utf8_char_at(const std::string& s, size_t i) {
    int len = utf8_char_len(s, i);
    return s.substr(i, len);
}

// ---------------------------------------------------------------------------
// Word list loading
// ---------------------------------------------------------------------------

static void load_wordlist(const std::string& path) {
    std::ifstream f(path);
    if (!f) throw std::runtime_error("Cannot open word list: " + path);
    std::string line;
    int cur_len = 0;
    while (std::getline(f, line)) {
        if (line.substr(0, 5) == "!!!!!") {
            cur_len = std::stoi(line.substr(5));
            g_max_word_len = std::max(g_max_word_len, cur_len);
        } else if (!line.empty()) {
            g_words.insert(line);
            // Add every Unicode character of every word to the alphabet set,
            // so multi-char-only chars (like 辰 or 光 in 辰光) are recognized
            // as alphabetic even when they don't appear as standalone words.
            size_t j = 0;
            while (j < line.size()) {
                int clen = utf8_char_len(line, j);
                g_alphabet.insert(line.substr(j, clen));
                j += clen;
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Tokenisation
// ---------------------------------------------------------------------------

// Apply LRLM to a chunk of consecutive in-alphabet characters.
static void tokenise_chunk(const std::string& chunk,
                            const std::vector<std::pair<size_t,int>>& offsets) {
    std::cout << ' ';  // leading space matches Python tokenizer output format
    size_t i = 0;
    while (i < offsets.size()) {
        bool found = false;
        int try_len = std::min(g_max_word_len, (int)(offsets.size() - i));
        // Try longest match first
        for (int len = try_len; len >= 1; len--) {
            size_t byte_start = offsets[i].first;
            size_t byte_end   = offsets[i + len - 1].first + offsets[i + len - 1].second;
            std::string candidate = chunk.substr(byte_start, byte_end - byte_start);
            if (g_words.count(candidate)) {
                std::cout.write(chunk.data() + byte_start, byte_end - byte_start);
                std::cout << ' ';
                i += len;
                found = true;
                break;
            }
        }
        if (!found) {
            std::cout.write(chunk.data() + offsets[i].first, offsets[i].second);
            std::cout << ' ';
            i++;
        }
    }
}

// Process stdin line by line:
//   - Consecutive in-alphabet chars are collected into a chunk and tokenised.
//   - Non-alphabet chars are passed through unchanged.
static void process_stream() {
    std::string line;
    while (std::getline(std::cin, line)) {
        std::string cur_chunk;
        size_t i = 0;
        while (i <= line.size()) {
            if (i == line.size()) {
                if (!cur_chunk.empty()) {
                    tokenise_chunk(cur_chunk, utf8_offsets(cur_chunk));
                    cur_chunk.clear();
                }
                std::cout << '\n';
                break;
            }
            int len = utf8_char_len(line, i);
            std::string ch = line.substr(i, len);
            if (g_alphabet.count(ch)) {
                cur_chunk += ch;
            } else {
                if (!cur_chunk.empty()) {
                    tokenise_chunk(cur_chunk, utf8_offsets(cur_chunk));
                    cur_chunk.clear();
                }
                std::cout.write(line.data() + i, len);
            }
            i += len;
        }
    }
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

int main(int argc, char* argv[]) {
    if (argc < 2) {
        std::cerr << "Usage: " << argv[0] << " <wordlist.txt>\n";
        std::cerr << "  wordlist.txt is generated by: python3 autotok_scraper.py 0\n";
        return 1;
    }
    try {
        load_wordlist(argv[1]);
    } catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << '\n';
        return 1;
    }
    process_stream();
    return 0;
}
